const links = {
  analysis: ['process', 'knowledge'],
  ability: ['index'],
  abstract_data_type: ['data_type', 'implementation'],
  abstraction: ['notion', 'observer', 'empirical_evidence'],
  agent: ['entity', 'computation'],
  algebra: ['symbol', 'mathematics', 'structure', 'matrix'],
  algorithm: ['data', 'reason', 'operation'],
  anchor: ['html', 'document'],
  answer: ['reactivity', 'linguistics'],
  antireflexivity: ['binary_relation', 'set'],
  antisymmetry: ['binary_relation', 'set'],
  api: ['application', 'programming', 'interface'],
  application: ['software'],
  application_software: ['computer_game', 'web_browser', 'text_editor'],
  architecture: ['art', 'design'],
  arithmetic: ['number', 'programming', 'abstraction', 'operator', 'mathematics'],
  array: ['associative_array', 'linked_list', 'array_data_type', 'array_data_structure'],
  array_data_structure: ['tuple', 'matrix'],
  array_data_type: ['abstract_data_type'],
  art: ['beauty'],
  ascii: ['telecommunications', 'character'],
  associative_array: ['hashtable'],
  atom_text_editor: ['github', 'open_source', 'git'],
  authentification: ['username', 'password', 'data_security'],
  authorization: ['index'],
  axiom: ['mathematics'],
  batch_program: ['programming', 'computer', 'interactive_program'],
  beauty: ['life'],
  belief: ['state', 'mind', 'empirical_evidence'],
  binary_relation: ['relation', 'set'],
  biology: ['life', 'function', 'structure'],
  bitwise_operation: ['bit', 'operation', 'computation', 'arithmetic'],
  brain: ['system', 'nerve', 'biology'],
  c_programming_language: ['structure', 'programming', 'operating_system', 'unix'],
  category: ['morphism', 'category_theory'],
  category_theory: ['category', 'mathematics', 'theory', 'morphism'],
  change: ['state', 'function', 'time'],
  character: ['information', 'symbol', 'graph', 'character_set'],
  character_set: ['encoding', 'ascii', 'unicode', 'punycode'],
  circuit: ['electronics', 'computer'],
  code: ['programmer', 'programming_language'],
  code_reusability: ['function', 'software_library'],
  codec: ['signal', 'stream'],
  collection: ['quantity', 'data', 'operator', 'problem'],
  command_line_interface: ['user_interface', 'computer'],
  communication: ['meaning', 'semiotics', 'information','system', 'sign'],
  communications_protocol: ['WWW', 'communication', 'SSL', 'http'],
  component: ['whole', 'computer'],
  compiler: ['machine_code', 'execution', 'interpreter'],
  composition: ['structure', 'component', 'function'],
  computation: ['algorithm', 'conceptual_model'],
  computer: ['computer_program', 'cpu', 'memory'],
  computer_game: ['interactive_program', 'experience'],
  computer_network: ['computer', 'telecommunications', 'communications_protocol'],
  computer_program: ['instruction', 'computer', 'algorithm', 'batch_program', 'interactive_program'],
  computer_science: ['representation', 'information', 'process_automation'],
  concept: ['abstraction', 'idea'],
  conceptual_model: ['composition', 'mental_model', 'representation', 'concept'],
  concurrent_computing: ['sequence', 'time'],
  consciousness: ['quality'],
  constant: ['change', 'value'],
  constructed_language: ['grammar', 'vocabulary', 'communication'],
  context: ['expression', 'state', 'text'],
  control_flow: ['switch'],
  control_system: ['device', 'system'],
  convention: ['society', 'communication'],
  cpu: ['arithmetic', 'logic', 'operation', 'circuit'],
  cryptography: ['md5', 'cypher', 'hash_function', 'cryptographic_protocol'],
  cryptographic_protocol: ['SSL', 'TSL'],
  culture: ['knowledge', 'art', 'belief'],
  cypher: ['algorithm', 'cryptography'],
  data: ['time', 'illustration', 'variable', 'set', 'value', 'graph', 'data_structure'],
  data_definition: ['program_design'],
  data_integrity: ['md5', 'immutability'],
  data_security: ['authentification', 'authorization','cryptography'],
  data_structure: ['data', 'structure', 'abstract_data_type', 'array'],
  design: ['convention', 'architecture', 'circuit'],
  device: ['tool', 'electronics'],
  document: ['api', 'web_browser', 'DOM'],
  DOM: ['html', 'api', 'javascript'],
  electromagnetism: ['physics'],
  electronics: ['device', 'circuit'],
  empirical_evidence: ['observer'],
  entity: ['reflexivity', 'antireflexivity'],
  encoding: ['code', 'cryptography', 'cipher'],
  energy: ['form', 'physics', 'E=m*c2'],
  ethics: ['philosophy'],
  event_handlers: ['interactive_program'],
  events: ['interactive_program'],
  execution: ['computer_program'],
  experience: ['index'],
  expression: ['value', 'variable', 'constant', 'operator', 'function'],
  file: ['data', 'paper', 'information_system'],
  file_system: ['file', 'data'],
  form: ['shape'],
  formal_system: ['formal_system_structure', 'geometry'],
  formal_system_structure: ['grammar', 'inference', 'axiom'],
  function: ['value', 'set', 'instruction', 'programming'],
  geometry: ['shape', 'space', 'visualization'],
  git: ['semver', 'command_line_interface', 'linux'],
  github: ['git'],
  goal: ['agent', 'set', 'state', 'system'],
  grammar: ['language', 'axiom'],
  graph: ['visualization'],
  graphical_user_interface: ['user_interface', 'icon'],
  GSM: ['telecommunications', 'network', 'wireless_communication'],
  hardware: ['collection', 'computer', 'system'],
  hashtable: ['data_structure'],
  hash_function: ['function'],
  hierarchy: ['category'],
  html: ['semantics', 'programming_language'],
  http: ['WWW', 'communications_protocol'],
  human: ['tool', 'brain', 'society'],
  hyperlink: ['html', 'document', 'anchor'],
  icon: ['graphical_user_interface', 'index'],
  IDE: ['text_editor', 'process_automation'],
  idea: ['mental_model', 'image', 'abstraction'],
  identification: ['process'],
  illustration: ['subject', 'representation', 'graph'],
  immutability: ['constant', 'data_structure'],
  implementation: ['application', 'design', 'execution', 'idea', 'standard'],
  inference: ['logic', 'axiom', 'process'],
  information: ['data', 'observer', 'question'],
  information_system: ['information', 'system', 'communication'],
  image: ['graphics', 'object', 'data_encoding'],
  index: ['language', 'cryptography', 'sequence', 'operating_system', 'node_js'],
  interprocess_communication: ['index'],
  io_operation: ['stream'],
  instruction: ['cpu', 'programming', 'computer'],
  interactive_program: ['events', 'event_handlers'],
  interface: ['system', 'hardware', 'software', 'computer', 'user_interface'],
  internet: ['internet_protocol', 'network', 'device'],
  internet_protocol: ['tcp_ip', 'http', 'websocket'],
  interpreter: ['execution', 'compiler', 'linker', 'machine_code'],
  iteration: ['process', 'goal'],
  javascript: ['io_operation', 'web_browser', 'html'],
  JSON: ['data_encoding', 'javascript', ],
  knowledge: ['information', 'observer', 'mindmap'],
  language: ['ability', 'human', 'system', 'communication'],
  learning: ['brain', 'io_operation'],
  life: ['energy'],
  linguistics: ['science', 'context', 'meaning', 'form'],
  linked_list: ['sequence', 'computer_science'],
  linux: ['open_source', 'unix', 'posix', 'operating_system'],
  logic: ['philosophy', 'reason'],
  machine_code: ['instruction', 'execution', 'computer'],
  making_examples: ['program_design', 'testing'],
  mathematics: ['knowledge', 'quantity', 'change', 'geometry', 'algebra'],
  matrix: ['array', 'index', 'symbol', 'expression'],
  matter: ['physics', 'index'],
  md5: ['hash_function', 'data_integrity'],
  meaning: ['communication', 'context'],
  memory: ['process', 'consciousness', 'encoding'],
  mental_model: ['thought'],
  mind: ['consciousness', 'human', 'set'],
  morphism: ['mathematics', 'structure'],
  nature: ['index'],
  nerve: ['index'],
  network: ['system', 'computer_network', 'social_network', 'structure'],
  node_js: ['javascript', 'npm', 'package_manager', 'SSL'],
  notation: ['character', 'convention'],
  notion: ['mind', 'relation', 'variable'],
  npm: ['package_manager', 'node_js', 'JSON'],
  number: ['computation', 'mathematics'],
  observer: ['information', 'interpreter'],
  object: ['entity', 'property', 'data_structure', 'procedure'],
  open_source: ['index'],
  operating_system: ['hardware', 'file_system', 'unix', 'linux', 'windows_os'],
  operation: ['instruction', 'control_flow', 'bitwise_operation'],
  operator: ['function', 'mathematics', 'computer'],
  package_manager: ['software', 'software_library', 'software_installation'],
  partial_order: ['transitivity', 'reflexivity', 'antisymmetry'],
  password: ['username', 'data_security'],
  pattern: ['iteration', 'design'],
  philosophy: ['reality', 'ethics', 'idea', 'religion', 'science'],
  physics: ['nature', 'analysis', 'matter', 'energy'],
  pipeline: ['index'],
  problem: ['situation'],
  procedure: ['code_reusability', 'design_pattern', 'program_design'],
  process: ['operating_system', 'concurrent_computing'],
  process_automation: ['control_system'],
  program_design: ['structure', 'data_definition', 'testing', 'making_examples'],
  programmer: ['code'],
  programming: ['execution', 'IDE', 'computer_program', 'data', 'learning'],
  programming_language: ['constructed_language', 'application_software', 'c_programming_language', 'syntax'],
  property: ['component', 'entity'],
  punycode: ['ascii', 'unicode'],
  quality: ['property', 'convention', 'standard'],
  quantity: ['property', 'mathematics', 'number', 'arithmetic'],
  question: ['answer', 'linguistics'],
  radio: ['wireless_communication', 'electromagnetism'],
  reality: ['human', 'observer'],
  reason: ['consciousness', 'logic'],
  reactivity: ['index'],
  reflexivity: ['relation', 'notation'],
  relation: ['function', 'theory', 'mathematics', 'code_reusability'],
  relationship: ['relation', 'set'],
  religion: ['index'],
  representation: ['relationship', 'collection'],
  science: ['reality', 'observer', 'religion'],
  semantics: ['meaning', 'semiotics'],
  semiotics: ['communication', 'sign'],
  semver: ['convention', 'software'],
  sequence: ['object', 'binary_relation', 'reflexivity', 'antisymmetry', 'transitivity'],
  set: ['object', 'collection', 'set_theory'],
  set_theory: ['formal_system', 'mathematics', 'theory'],
  shape: ['form', 'index'],
  sign: ['meaning', 'interpreter', 'codec'],
  signal: ['index'],
  situation: ['state', 'entity'],
  space: ['index'],
  social_network: ['structure', 'actor'],
  society: ['human', 'culture'],
  software: ['computer_program', 'cpu'],
  software_library: ['programmer', 'tool', 'compiler'],
  SSL: ['TLS', 'data_security', 'cryptographic_protocol'],
  standard: ['convention', 'index'],
  state: ['computer_program', 'information', 'situation'],
  stream: ['sequence', 'data'],
  structure: ['notion', 'pattern', 'hierarchy', 'network'],
  subject: ['philosophy', 'grammar', 'consciousness'],
  symbol: ['representation', 'object', 'illustration', 'idea', 'belief'],
  syntax: ['grammar', 'vocabulary', 'language', 'meaning'],
  system: ['set', 'component', 'file_system'],
  switch: ['control_flow'],
  tcp_ip: ['internet', 'communications_protocol'],
  telecommunications: ['radio', 'GSM'],
  testing: ['program_design', 'making_examples'],
  text: ['punycode', 'ascii', 'unicode'],
  text_editor: ['vim', 'atom_text_editor', 'computer_program'],
  text_user_interface: ['graphical_user_interface', 'command_line_interface'],
  theory: ['reason', 'science', 'abstraction'],
  thought: ['idea', 'human', 'brain'],
  time: ['change', 'universe'],
  TLS: ['SSL', 'cryptographic_protocol'],
  tool: ['goal'],
  transitivity: ['partial_order', 'relation', 'mathematics'],
  tuple: ['number', 'set', 'partial_order'],
  unicode: ['character_set', 'text', 'encoding', 'standard'],
  universe: ['collection'],
  unix: ['unix_philosophy', 'unix_shell'],
  unix_filesystem: ['pipeline', 'interprocess_communication'],
  unix_philosophy: ['unix_shell', 'unix_filesystem'],
  unix_shell: ['user_interface', 'command_line_interface', 'programming_language', 'file_system', 'unix'],
  uri: ['text', 'identification'],
  user_interface: ['command_line_interface', 'graphical_user_interface'],
  username: ['password', 'data_security'],
  value: ['expression'],
  variable: ['algebra', 'information', 'value'],
  vim: ['text_user_interface', 'open_source'],
  windows_os: ['software', 'operating_system', 'unix'],
  visualization: ['communication', 'image', 'illustration', 'idea', 'thought'],
  vocabulary: ['word', 'set', 'language'],
  web_browser: ['software', 'WWW', 'DOM'],
  websocket: ['communications_protocol'],
  whole: ['communication', 'interface', 'component'],
  wireless_communication: ['information', 'electromagnetism', 'radio'],
  word: ['property', 'meaning', 'symbol'],
  WWW: ['uri', 'hyperlink', 'internet']
};

export default links;
