const links = {
  ability: ['index'],
  abstract_data_type: ['data_type', 'implementation'],
  abstraction: ['notion', 'observer', 'empirical_evidence'],
  agent: ['entity', 'computation'],
  agile_software_development: ['software_development', 'pid_controller'],
  algebra: ['symbol', 'mathematics', 'structure', 'matrix'],
  algorithm: ['data', 'reason', 'operation', 'chomsky_hierarchy'],
  analog_signal: ['index'],
  analysis: ['process', 'knowledge'],
  anchor: ['html', 'document'],
  animal: ['human', 'brain', 'organism'],
  animation: ['illusion', 'motion'],
  answer: ['reactivity', 'linguistics'],
  antireflexivity: ['binary_relation', 'set'],
  antisymmetry: ['binary_relation', 'set'],
  api: ['application', 'programming', 'interface', 'socket'],
  application: ['software', 'distributed_application', 'network_application', 'SOA'],
  application_layer: ['network_model', 'socket'],
  application_software: ['computer_game', 'web_browser', 'text_editor'],
  architecture: ['art', 'design', 'software_architechture'],
  arithmetic: ['number', 'programming', 'abstraction', 'operator', 'mathematics'],
  array: ['associative_array', 'linked_list', 'array_data_type', 'array_data_structure'],
  array_data_structure: ['tuple', 'matrix'],
  array_data_type: ['abstract_data_type'],
  art: ['beauty'],
  ascii: ['telecommunications', 'character'],
  associative_array: ['hashtable'],
  atom: ['physics'],
  atom_text_editor: ['github', 'open_source', 'git'],
  authentification: ['username', 'password', 'data_security'],
  authorization: ['index', 'public_access', 'private_access'],
  automation: ['control_system', 'pid_controller', 'process_automation'],
  axiom: ['mathematics'],
  AJAX: ['index'],
  batch_program: ['io_operation', 'computer', 'interactive_program'],
  beauty: ['life'],
  belief: ['state', 'mind', 'empirical_evidence'],
  binary_relation: ['relation', 'set'],
  biology: ['life', 'function', 'structure'],
  bit: ['bitwise_operation'],
  bitcoin: ['p2p_network', 'cryptocurrency', 'open_source'],
  bitwise_operation: ['bit', 'operation', 'computation', 'arithmetic'],
  brain: ['system', 'nerve', 'biology', 'animal'],
  Blockchain: ['index', 'bitcoin', 'database'],
  c_plus_plus: ['object_oriented_programming', 'system_programming', 'desktop_application', 'index'],
  c_programming_language: ['structure', 'programming', 'operating_system', 'unix', 'c_plus_plus'],
  category: ['morphism', 'category_theory'],
  category_theory: ['category', 'mathematics', 'theory', 'morphism'],
  change: ['state', 'function', 'time'],
  character: ['information', 'symbol', 'graph', 'character_set'],
  character_set: ['encoding', 'ascii', 'unicode', 'punycode'],
  chinese_room: ['intuiton_pump', 'strong_AI'],
  chomsky_hierarchy: ['algorithm', 'hierarchy', 'grammar', 'turing_machine'],
  class_oop: ['object_oriented_programming', 'inheritance_oop', 'polymorphism_oop', 'hierarchy'],
  client: ['server', 'index', 'p2p_network'],
  client_server_model: ['server', 'client', 'information_technology'],
  closed_loop_control_system: ['control_system', 'feedback_control_system', 'open_loop_control_system'],
  circuit: ['electronics', 'computer'],
  code: ['programmer', 'programming_language', 'syntax'],
  code_reusability: ['function', 'software_library'],
  codec: ['signal', 'stream'],
  coffee: ['programmer'],
  cognition: ['brain', 'index', 'thought'],
  collection: ['quantity', 'data', 'operator', 'problem'],
  command_line_interface: ['user_interface', 'computer'],
  communication: ['component', 'meaning', 'semiotics', 'information','system', 'sign'],
  communications_protocol: ['WWW', 'communication', 'SSL', 'http'],
  compiler: ['machine_code', 'execution', 'interpreter'],
  component: ['whole', 'computer', 'system'],
  composition: ['structure', 'component', 'function'],
  computability: ['computation'],
  computation: ['algorithm', 'computability', 'conceptual_model', 'protocol'],
  computer: ['cpu', 'memory', 'operating_system', 'device'],
  computer_architecture: ['index', 'pipeline'],
  computer_game: ['interactive_program', 'experience'],
  computer_network: ['computer', 'telecommunications', 'internet', 'network'],
  computer_program: ['batch_program', 'interactive_program', 'instruction', 'algorithm'],
  computer_science: ['representation', 'information', 'process_automation'],
  concept: ['abstraction', 'idea'],
  conceptual_model: ['composition', 'mental_model', 'representation', 'concept'],
  concurrent_computing: ['sequence', 'time', 'dining_philosophers'],
  consciousness: ['quality', 'state'],
  constant: ['change', 'value'],
  constructed_language: ['grammar', 'vocabulary', 'communication'],
  content_management_system: ['tool', 'software'],
  context: ['expression', 'state', 'text'],
  control_flow: ['switch'],
  control_loop: ['control_system'],
  control_system: ['device', 'open_loop_control_system', 'closed_loop_control_system'],
  convention: ['society', 'communication'],
  cpu: ['arithmetic', 'logic', 'operation', 'circuit', 'io_operation'],
  cpu_operation: ['index', 'cpu'],
  cryptocurrency: ['digital_currency', 'index', 'Blockchain', 'cryptography', 'decentralization'],
  cryptography: ['md5', 'cypher', 'hash_function', 'cryptographic_protocol'],
  cryptographic_protocol: ['SSL', 'TSL'],
  culture: ['knowledge', 'art', 'belief', 'ethics'],
  cypher: ['algorithm', 'cryptography'],
  CGI: ['index', 'filmmaking'],
  data: ['illustration', 'variable', 'set', 'value', 'graph', 'data_structure'],
  database: ['index', 'data'],
  data_definition: ['program_design'],
  data_integrity: ['md5', 'immutability'],
  data_security: ['authentification', 'authorization','cryptography'],
  data_structure: ['data', 'structure', 'abstract_data_type', 'array'],
  decentralization: ['index', 'cybernetics'],
  design: ['convention', 'architecture', 'circuit'],
  desktop_application: ['index', 'c_plus_plus'],
  device: ['tool', 'electronics', 'TV_set', 'computer'],
  digital_currency: ['index', 'cryptocurrency'],
  digital_recording: ['index', 'recording'],
  dining_philosophers: ['concurrent_computing', 'intuition_pump'],
  distributed_application: ['application', 'distributed_system', 'p2p_network'],
  distributed_system: ['system', 'distributed_application'],
  document: ['api', 'web_browser', 'DOM'],
  DOM: ['html', 'api', 'javascript'],
  dynamic_type_checking: ['prototype_oop', 'static_type_checking'],
  electromagnetism: ['physics', 'electron'],
  electron: ['atom', 'electronics', 'electromagnetism'],
  electronics: ['device', 'circuit', 'transistor', 'electron'],
  empirical_evidence: ['observer', 'matter', 'belief'],
  entity: ['reflexivity', 'antireflexivity'],
  encoding: ['code', 'cryptography', 'cipher'],
  energy: ['form', 'physics', 'E=m*c2'],
  ethics: ['philosophy'],
  event_handler: ['interactive_program'],
  event: ['interactive_program'],
  execution: ['computer_program', 'instruction'],
  experience: ['index'],
  expression: ['value', 'variable', 'constant', 'operator', 'function'],
  'E=m*c^2': ['energy'],
  feedback_control_system: ['closed_loop_control_system'],
  file: ['data', 'paper', 'information_system'],
  file_system: ['file', 'data', 'unix_filesystem'],
  film: ['photography', 'animation', 'filmmaking'],
  filmmaking: ['recording', 'CGI'],
  filter: ['stream', 'cpu'],
  firstclass_function: ['value', 'function', 'programming'],
  form: ['shape'],
  formal_system: ['formal_system_structure', 'geometry'],
  formal_system_structure: ['grammar', 'inference', 'axiom'],
  function: ['value', 'set', 'instruction', 'programming'],
  game_engine: ['index', 'computer_game'],
  geometry: ['shape', 'space', 'visualization'],
  git: ['semver', 'command_line_interface', 'linux'],
  github: ['git', 'atom_text_editor', 'markdown'],
  goal: ['agent', 'set', 'state', 'system', 'tool'],
  grammar: ['language', 'axiom'],
  graph: ['visualization', 'information'],
  graphical_user_interface: ['user_interface', 'icon'],
  GSM: ['telecommunications', 'network', 'wireless_communication'],
  hardware: ['collection', 'computer', 'system', 'software'],
  hashtable: ['data_structure'],
  hash_function: ['function'],
  hierarchy: ['category', 'pyramid'],
  html: ['semantics', 'programming_language', 'anchor'],
  http: ['WWW', 'communications_protocol', 'http_request', 'http_response'],
  http_request: ['index', 'server', 'client'],
  http_response: ['index', 'server', 'client'],
  human: ['tool', 'brain', 'society', 'philosophy'],
  hyperlink: ['html', 'document', 'anchor'],
  icon: ['graphical_user_interface', 'index'],
  IDE: ['text_editor', 'process_automation'],
  idea: ['mental_model', 'image', 'abstraction'],
  identification: ['process'],
  illusion: ['index'],
  illustration: ['subject', 'representation', 'graph'],
  image: ['graphics', 'object', 'data_encoding'],
  immutability: ['constant', 'data_structure'],
  implementation: ['application', 'design', 'execution', 'idea', 'standard'],
  index: ['socket', 'software_development', 'content_management_system'],
  inference: ['logic', 'axiom', 'process'],
  information: ['data', 'observer', 'question', 'visualization'],
  information_system: ['information', 'system', 'communication'],
  information_technology: ['client_server_model', 'computer', 'computer_network', 'TV_set', 'telephone'],
  inheritance_oop: ['object_oriented_programming'],
  instruction: ['cpu', 'programming', 'computer', 'machine_code'],
  intelligence: ['learning', 'cognition', 'reason'],
  interprocess_communication: ['index'],
  interactive_program: ['event', 'event_handler', 'computer_program'],
  interface: ['system', 'hardware', 'software', 'computer', 'user_interface'],
  internet: ['tcp_ip', 'computer_network', 'WWW', 'http', 'p2p_network'],
  internet_protocol: ['tcp_ip', 'http', 'websocket'],
  interpreter: ['execution', 'compiler', 'linker', 'machine_code'],
  intuition_pump: ['dining_philosophers', 'chinese_room', 'ship_of_theseus'],
  io_operation: ['computer_science','stream', 'software', 'function'],
  iteration: ['process', 'goal'],
  javascript: ['io_operation', 'web_browser', 'html', 'node_js', 'DOM', 'AJAX'],
  JSON: ['data_encoding', 'javascript', ],
  knowledge: ['information', 'observer', 'mindmap', 'paradigm'],
  language: ['ability', 'human', 'system', 'communication'],
  learning: ['brain', 'io_operation', 'programming'],
  life: ['energy'],
  linguistics: ['science', 'context', 'meaning', 'form'],
  linked_list: ['sequence', 'computer_science'],
  linker: ['interpreter'],
  linux: ['open_source', 'unix', 'posix', 'operating_system'],
  logic: ['philosophy', 'reason'],
  machine_code: ['instruction', 'execution', 'computer'],
  making_examples: ['program_design', 'testing'],
  markdown: ['github'],
  mathematics: ['knowledge', 'quantity', 'change', 'geometry', 'algebra'],
  matrix: ['array', 'index', 'symbol', 'expression'],
  matter: ['physics'],
  md5: ['hash_function', 'data_integrity'],
  meaning: ['communication', 'context'],
  memory: ['process', 'consciousness', 'encoding'],
  mental_model: ['thought', 'idea'],
  microservices: ['software_architecture'],
  mind: ['consciousness', 'human', 'set'],
  mindmap: ['knowledge', 'visualization', 'graph'],
  monolith: ['software_architecture'],
  morphism: ['mathematics', 'structure'],
  motion: ['index', 'three_Newton_laws'],
  nature: ['physics'],
  nerve: ['index'],
  network: ['system', 'computer_network', 'social_network', 'structure'],
  network_application: ['remote_access', 'application', 'network'],
  network_model: ['conceptual_model', 'computer_network'],
  node_js: ['javascript', 'web_server', 'npm', 'package_manager', 'SSL', 'tcp_ip'],
  notation: ['character', 'convention'],
  notion: ['mind', 'relation', 'variable'],
  npm: ['package_manager', 'node_js', 'JSON'],
  number: ['computation', 'mathematics'],
  observer: ['information', 'reality', 'science', 'empirical_evidence'],
  object: ['entity', 'property', 'data_structure', 'procedure'],
  object_code: ['index'],
  object_oriented_programming: ['programming_paradigm', 'class_oop', 'prototype_oop', 'object_composition'],
  object_composition: ['object_oriented_programming'],
  open_loop_control_system: ['control_system', 'closed_loop_control_system'],
  open_source: ['index'],
  operating_system: ['hardware', 'file_system', 'network', 'unix', 'linux', 'windows_os'],
  operation: ['instruction', 'control_flow', 'bitwise_operation'],
  operator: ['function', 'mathematics', 'computer'],
  organism: ['life'],
  package_manager: ['software', 'software_library', 'software_installation'],
  p2p_network: ['index', 'computer_network', 'client', 'server'],
  paradigm: ['knowledge', 'programming_paradigm'],
  partial_order: ['transitivity', 'reflexivity', 'antisymmetry'],
  password: ['username', 'data_security'],
  pattern: ['iteration', 'design'],
  philosophy: ['reality', 'ethics', 'idea', 'religion', 'science', 'intuition_pump'],
  photography: ['index'],
  physics: ['nature', 'analysis', 'matter', 'energy'],
  pid_controller: ['automation', 'closed_loop_control_system'],
  pipeline: ['index', 'stream'],
  polymorphism_oop: ['class_oop', 'prototype_oop'],
  private_access: ['index', 'authorization'],
  problem: ['situation'],
  procedure: ['code_reusability', 'design_pattern', 'program_design'],
  process: ['operating_system', 'concurrent_computing'],
  process_automation: ['control_system', 'computer_science'],
  program_design: ['structure', 'data_definition', 'testing', 'making_examples'],
  programmer: ['code', 'coffee'],
  programming: ['execution', 'IDE', 'computer_program', 'data', 'learning'],
  programming_language: ['constructed_language', 'application_software', 'c_programming_language'],
  programming_paradigm: ['paradigm', 'object_oriented_programming', 'type_system'],
  property: ['component', 'entity'],
  protocol: ['communication', 'computation'],
  prototype_oop: ['object_oriented_programming', 'polymorphism_oop', 'dynamic_type_checking'],
  public_access: ['index'],
  punycode: ['ascii', 'unicode'],
  pyramid: ['index', 'hierarchy'],
  quality: ['property', 'convention', 'standard'],
  quantity: ['property', 'mathematics', 'number', 'arithmetic'],
  question: ['answer', 'linguistics', 'information'],
  radio: ['wireless_communication', 'electromagnetism'],
  reality: ['human', 'observer'],
  reason: ['consciousness', 'logic', 'intelligence'],
  reactivity: ['index'],
  recording: ['index', 'digital_recording', 'analog_signal'],
  recursion: ['computability'],
  reflexivity: ['antireflexivity', 'relation', 'notation'],
  relation: ['function', 'theory', 'mathematics', 'code_reusability'],
  relationship: ['relation', 'set'],
  religion: ['index', 'philosophy'],
  remote_access: ['network_application', 'virtual_private_network'],
  replaceable_parts: ['standard', 'index'],
  representation: ['relationship', 'collection'],
  science: ['reality', 'observer', 'religion'],
  semantics: ['meaning', 'semiotics'],
  semiotics: ['communication', 'sign'],
  semver: ['convention', 'software'],
  sequence: ['object', 'binary_relation', 'reflexivity', 'antisymmetry', 'transitivity'],
  server: ['web_server', 'client', 'p2p_network', 'client_server_model'],
  set: ['object', 'collection', 'set_theory'],
  set_theory: ['formal_system', 'mathematics', 'theory'],
  shape: ['form', 'index'],
  ship_of_theseus: ['intuition_pump'],
  sign: ['meaning', 'interpreter', 'codec'],
  signal: ['interprocess_communication', 'unix'],
  situation: ['state', 'entity'],
  social_network: ['structure', 'actor'],
  society: ['human', 'culture'],
  socket: ['application_layer', 'transportation_layer', 'api'],
  software: ['application', 'computer_program', 'cpu', 'cpu_operation'],
  software_architechture: ['microservices', 'monolith'],
  software_development: ['software', 'agile_software_development'],
  software_framework: ['index', 'abstraction', 'api'],
  software_library: ['programmer', 'tool', 'compiler'],
  software_platform: ['software', 'object code', 'computer_architecture'],
  space: ['geometry'],
  standard: ['convention', 'index', 'replaceable_parts'],
  state: ['computer_program', 'information', 'situation'],
  static_type_checking: ['dynamic_type_checking', 'type_system'],
  stream: ['sequence', 'data', 'batch_program', 'filter'],
  strong_AI: ['chinese_room'],
  structure: ['notion', 'pattern', 'hierarchy', 'network'],
  subject: ['philosophy', 'language', 'experience', 'consciousness'],
  symbol: ['representation', 'object', 'illustration', 'idea', 'belief'],
  syntax: ['grammar', 'vocabulary', 'language', 'meaning'],
  system: ['component', 'file_system', 'distributed_system'],
  system_programming: ['software_platform', 'operating_system', 'game_engine'],
  switch: ['control_flow'],
  SOA: ['application'],
  SSL: ['TLS', 'data_security', 'cryptographic_protocol'],
  tcp_ip: ['internet', 'communications_protocol'],
  telecommunications: ['radio', 'GSM', 'computer_network'],
  telephone: ['information_technology', 'telecommunications'],
  television: ['index', 'television_program'],
  television_program: ['index', 'film'],
  testing: ['program_design', 'making_examples'],
  text: ['punycode', 'ascii', 'unicode'],
  text_editor: ['vim', 'atom_text_editor', 'computer_program'],
  text_user_interface: ['graphical_user_interface', 'command_line_interface'],
  three_Newton_laws: ['motion', '1st_Newton_law', '2nd_Newton_law', '3rd_Newton_law'],
  theory: ['reason', 'science', 'abstraction'],
  thought: ['idea', 'human', 'brain'],
  time: ['change', 'universe'],
  tool: ['goal', 'human', 'device'],
  transistor: ['circuit', 'electronics'],
  transitivity: ['partial_order', 'relation', 'mathematics'],
  transportation_layer: ['network_model', 'socket'],
  turing_machine: ['chomsky_hierarchy'],
  tuple: ['number', 'set', 'partial_order'],
  TLS: ['SSL', 'cryptographic_protocol', 'data_security'],
  TV_set: ['index', 'television', 'device'],
  type_system: ['programming_paradigm'],
  unicode: ['character_set', 'text', 'encoding', 'standard'],
  universe: ['collection', 'entity'],
  unix: ['unix_philosophy', 'unix_shell'],
  unix_filesystem: ['pipeline', 'interprocess_communication'],
  unix_philosophy: ['unix_shell', 'unix_filesystem', 'philosophy'],
  unix_shell: ['user_interface', 'command_line_interface', 'programming_language', 'file_system', 'unix'],
  uri: ['text', 'identification'],
  user_interface: ['command_line_interface', 'graphical_user_interface'],
  username: ['password', 'data_security'],
  value: ['expression', 'firstclass_function'],
  variable: ['algebra', 'information', 'value'],
  vim: ['text_user_interface', 'open_source'],
  virtual_private_network: ['remote_access'],
  visualization: ['communication', 'image', 'illustration', 'idea', 'thought'],
  vocabulary: ['word', 'set', 'language'],
  web_browser: ['software', 'WWW', 'DOM', 'web_server'],
  web_server: ['server', 'web_browser', 'http_request', 'http_response'],
  websocket: ['communications_protocol'],
  whole: ['communication', 'interface', 'component'],
  windows_os: ['software', 'operating_system', 'unix'],
  wireless_communication: ['information', 'electromagnetism', 'radio'],
  word: ['property', 'meaning', 'symbol'],
  WWW: ['uri', 'hyperlink', 'internet', 'http', 'AJAX']
};

export default links;
